

services:
  web:
    build: .
    container_name: "leads_infinitos_web"
    ports:
      - "8000:8000"
    command: sh -c "python -c 'from app import init_db; init_db()' && gunicorn -b 0.0.0.0:8000 --timeout 30 --worker-class sync --workers 1 --max-requests 100 --max-requests-jitter 10 --preload app:app"
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEGA_API_URL=${MEGA_API_URL}
      - MEGA_API_TOKEN=${MEGA_API_TOKEN}
      - APIFY_TOKEN=${APIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOTMART_HOTTOK=${HOTMART_HOTTOK}
      - HOTMART_PRODUCT_ID=${HOTMART_PRODUCT_ID}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always
    networks:
      - dokploy-network

  worker:
    build: .
    container_name: "leads_infinitos_worker"
    command: python worker.py
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEGA_API_URL=${MEGA_API_URL}
      - MEGA_API_TOKEN=${MEGA_API_TOKEN}
      - APIFY_TOKEN=${APIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOTMART_HOTTOK=${HOTMART_HOTTOK}
      - HOTMART_PRODUCT_ID=${HOTMART_PRODUCT_ID}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always
    networks:
      - dokploy-network

  sender:
    build: .
    container_name: "leads_infinitos_sender"
    command: python worker_sender.py
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEGA_API_URL=${MEGA_API_URL}
      - MEGA_API_TOKEN=${MEGA_API_TOKEN}
      - APIFY_TOKEN=${APIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOTMART_HOTTOK=${HOTMART_HOTTOK}
      - HOTMART_PRODUCT_ID=${HOTMART_PRODUCT_ID}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
